version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: sentiment-analysis-api:latest
    container_name: sentiment-analysis-api
    restart: unless-stopped
    environment:
      - MODEL_PATH=/app/models/best_model.pt
      - PORT=5010
      - HOST=0.0.0.0
      - DEVICE=cuda # Change to cpu if not using GPU
    volumes:
      - ./data/models:/app/models
    ports:
      - "5010:5010"

  nginx:
    image: nginx:latest
    container_name: sentiment-analysis-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    deploy:
      replicas: 1

  prometheus:
    image: prom/prometheus:latest
    container_name: sentiment-analysis-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - "9090:9090"
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    container_name: sentiment-analysis-grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: sentiment-analysis-client:latest
    container_name: sentiment-analysis-client
    restart: unless-stopped
    ports:
      - "3001:80"
    depends_on:
      - nginx

volumes:
  prometheus_data:
  grafana_data:
