global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "sentiment-api"
    static_configs:
      - targets: ["localhost:5010"]
    metrics_path: "/api/stats"  # Default Prometheus metrics endpoint